#ifndef ARNOLD_CONSTANTS_H
#define ARNOLD_CONSTANTS_H

#pragma once

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define WINDOW_HEIGHT 640
#define WINDOW_WIDTH 800

#endif // ARNOLD_CONSTANTS_H
